envName: <+env.name>
appName: <+service.name> 
artifactImage: <+artifact.image> #from Harness Service Primary Artifact
containerPort: 80
servicePort: 80
createNamespace: true
namespace:  <+service.name>-<+env.name>
publicDomainName: <+serviceVariables.publicDomainName>
dnsSuffix: <+serviceVariables.dnsSuffix>

vueAppApiUrl: <+serviceVariables.vueAppApiUrl>
vueAppPrerenderUrl: <+serviceVariables.vueAppPrerenderUrl>
vueAppLanguages: <+serviceVariables.vueAppLanguages>
vueAppZohoEndpoint: <+serviceVariables.vueAppZohoEndpoint>