apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.appName}}-{{.Values.envName}}-config
  namespace: {{.Values.namespace}}
data:
  VUE_APP_API_URL: {{.Values.vueAppApiUrl}}
  VUE_APP_PRERENDER_URL: {{.Values.vueAppPrerenderUrl}}
  VUE_APP_LANGUAGES: {{.Values.vueAppLanguages}}
  VUE_APP_ZOHO_ENDPOINT: {{.Values.vueAppZohoEndpoint}}
