# note: We explicitly create each language subdomain, rather than a wildcard domain
# as wildcards are not supportd by http01 cert-manager ClusterIssuer

{{- if .Values.ingressDomainName}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{.Values.namespace}}
  name: vn-{{.Values.appName}}-{{.Values.envName}}-ingress
  annotations:     
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - vn.{{.Values.ingressDomainName}}
    secretName: vn-{{.Values.appName}}-{{.Values.envName}}-tls
  rules:
  - host: vn.{{.Values.ingressDomainName}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{.Values.appName}}-{{.Values.envName}}-svc
            port:
              number: {{.Values.servicePort}}
  ingressClassName: nginx

  {{- end}}